### ISSUE TITLE
Very interesting mod idea, but I don't know how to put it on Among Us

### ISSUE THREAD

**Issue by pivattidev** [ZiadMontaser/VentDigger#1]
Hi. I found the idea of the mod very interesting and downloaded it. But I don't know how to put the files. Is there any way for me to contact you?

**Comment by ZiadMontaser** [comment]
unzip release content in the root among us forlder
![image](https://user-images.githubusercontent.com/62536773/107880219-4f523400-6e92-11eb-8fec-7c04c786b556.png)
