### ISSUE TITLE
Modded handshake

### ISSUE THREAD

**Issue by Andrzejone** [ZiadMontaser/VentDigger#2]
![image](https://user-images.githubusercontent.com/39127677/108083162-1624ea00-7073-11eb-91f6-082343b22573.png)

That's the problem. Root folder, steam version (clean install) Won't work on any server (Impostor too)

**Comment by ZiadMontaser** [comment]
?

**Comment by ZiadMontaser** [comment]
you have to use reactor fork of impostor 
https://github.com/NuclearPowered/Impostor

**Comment by Andrzejone** [comment]
I did. The same happens.
![image](https://user-images.githubusercontent.com/39127677/108085215-62712980-7075-11eb-9857-aaa0af799bf3.png)

**Comment by Elujla** [comment]
Hi, go to BepInEx\config and open gg.reactor.api config file with notepad.
Change Modded handshake from true to false.

**Comment by Andrzejone** [comment]
Już to dawno ogarnąłem, ale thx
